version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ./storage:/var/www/html/storage
    # depends_on:
      # - db
    networks:
      - laradrive-prod

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laradrive-prod

  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - laradrive-prod

# volumes:
  # db_data:

networks:
  laradrive-prod:
