// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table folders {
  id uuid [pk]
  name string [not null]
  created_by uuid [not null, ref: > users.id]
  parent_id uuid [ref: > folders.id]
  path string
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table files {
  id uuid [pk]
  name string [not null]
  folder_id uuid [ref: > folders.id]
  created_by uuid [not null, ref: > users.id]
  path string
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table users {
  id uuid [pk]
  username varchar
  role varchar
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table files_shares {
  id integer [primary key]
  file_id uuid [not null, ref: > files.id]
  user_id uuid [not null, ref: > users.id]
  created_by uuid [not null, ref: > users.id]
  created_at timestamp
  updated_at timestamp
}

Table files_stared {
  id integer [primary key]
  file_id uuid [not null, ref: > files.id]
  user_id uuid [not null, ref: > users.id]
  created_at timestamp
  updated_at timestamp
}


Ref: "files"."id" < "files"."name"
